services:
  app:
    image: docker.io/doriantrn/tempconverter:latest
    ports:
      - 5000:5000
    environment:
      - DB_USER=username
      - DB_PASS=supersecretpassword
      - DB_HOST=db
      - DB_NAME=dbname
      - STUDENT=Dorian Tarin
      - COLLEGE=Algebra University College
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tempconverter-net

  db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=username
      - MYSQL_PASSWORD=supersecretpassword
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 2s
      timeout: 10s
      retries: 10
    networks:
      - tempconverter-net
    volumes:
      - db-data:/var/lib/mysql

networks:
  tempconverter-net:
    driver: bridge

volumes:
  db-data:
