services:
  db:
    image:
      mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=tempconverter_db
      - MYSQL_USER=tempuser
      - MYSQL_PASWWORD=temppassword
    networks:
      - tempconverter-net
    
  app:
    image: doriantrn/tempconverter:latest
    environment:
      - DB_USER=tempuser
      - DB_PASS=temppassword
      - DB_HOST=db
      - DB_NAME=tempconverter_db
      - STUDENT=Dorian Tarin
      - COLLEGE=Algebra University College
    ports:
      - 5000:5000
    networks:
      - tempconverter-net
    depends_on:
      - db

networks:
  tempconverter-net:
    driver: bridge
