apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter-app
  template:
    metadata:
      labels:
        app: tempconverter-app
    spec:
      containers:
        - name: app
          image: docker.io/doriantrn/tempconverter:latest
          env:
            - name: DB_USER
              value: username
            - name: DB_PASS
              value: supersecretpassword
            - name: DB_HOST
              value: tempconverter-db
            - name: DB_NAME
              value: dbname
            - name: STUDENT
              value: "Dorian Tarin"
            - name: COLLEGE
              value: "Algebra University College"
          ports:
            - containerPort: 5000

