apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter
  namespace: tempconverter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter
  template:
    metadata:
      labels:
        app: tempconverter
    spec:
      containers:
        - name: tempconverter
          image: <your-dockerhub-username>/tempconverter:latest
          env:
            - name: DB_USER
              value: username
            - name: DB_PASS
              value: supersecretpassword
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: dbname
            - name: STUDENT
              value: "Dorian Tarin"
            - name: COLLEGE
              value: "Algebra University College"
          ports:
            - containerPort: 5000

