apiVersion: v1
kind: Service
metadata:
  name: tempconverter
  namespace: tempconverter
spec:
  type: NodePort
  selector: 
  app: tempconverter
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000

