apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tempconverter-db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: tempconverter-db
  template:
    metadata:
      labels: 
        app: tempconverter-db
    spec:
      containers:
        - name: db
          image: mysql:8
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: dbname
            - name: MYSQL_USER
              value: username
            - name: MYSQL_PASSWORD
              value: supersecretpassword
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-vol
